#!/usr/bin/env bash
# do stuff
RES=""
get_ip () {
	RES=$(dig +short "$2"."$1" | awk "{print}") # gotta learn how to use awk properly
}

if [ $# -lt 1 ]; then
	exit 1
elif [ $# -eq 1 ]; then
	subs=('www' 'lb-01' 'web-01' 'web-02')
	for i in "${subs[@]}"
	do
		get_ip "$1" "$i"
		echo "The subdomain $i is a A record and points to $RES"
	done
elif [ $# -eq 2 ]; then
	get_ip "$1" "$2"
	echo "The subdomain $2 is a A record and points to $RES"
fi
