#!/usr/bin/env bash
# Install nginx on web server
apt install -y nginx

sudo rm /var/www/html/*
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
Redirect 301 54.175.243.76/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 
