#!/usr/bin/env bash
# Install nginx on web server and set up redirections returning errors
apt install -y nginx

sudo rm -f /var/www/html/*
echo 'Hello World!' > /var/www/html/index.html
service nginx restart

rep_cmd="
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;	
	
	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
	}

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}"
echo -e  "$rep_cmd" > /etc/nginx/sites-available/default

service nginx reload
