#!/usr/bin/env bash
# Configure machine to host itszey.tech
apt update -y
apt install nginx -y
rm -rf /var/www/*
mkdir -p /var/www/itszey.tech/html

scr_angel="
<html>
        <head>
                <title>
                Site In progress
                </title>
        </head>

        <body style='color: white; background-color:black'>
                <p align=\"centre\"> <big> Good Morning <em><font color='pink' face='times new roman' >Angel</font></em></big></p>
                <p></p>
                <p> Thank you for always putting up with my dumb behaviour<br/>
                I promise to change and i love you very much.</p><hr/>
                <h6 align=\"centre\"> Site in progress </h6>
                <h3>
        </body>
</html>"

cmd="
server {
        add_header X-Served-By \"$(hostname)\";
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/itszey.tech/html;
        index index.html index.htm index.nginx-debian.html;

        server_name itszey.tech www.itszey.tech;

        error_page 404 /404.html;

        location / {
                try_files \$uri \$uri/ = 404;
        }

        location /angel {
                return 301 http://angel.itszey.tech;
        }

        location /404.html {
                internal;
                root /var/www/itszey.tech/html/;
        }

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}

server {
        listen 80;
        listen [::]:80;

        root /var/www/itszey.tech/html;
        index angel.html angel.htm;

        server_name angel.itszey.tech;

        location / {
                try_files \$uri \$uri/ = 404;
        }
}"

scr_index="
<html>
        <head>
                <title>
                Site In progress
                </title>
        </head>

        <body style='color: white; background-color:black'>
                <h1 style='text-align: centre'> Site in progress </h1> <hr/>
                <h3>
        </body>
</html>"

echo -e "$cmd" > /etc/nginx/sites-available/itszey.tech
ln /etc/nginx/sites-available/itszey.tech /etc/nginx/sites-enabled/
echo "$scr_angel" > /var/www/itszey.tech/html/angel.html
echo "$scr_index" > /var/www/itszey.tech/html/index.html
service nginx start
