#!/usr/bin/env bash
# Configure machine to host itszey.tech
sudo apt update -y
sudo apt install nginx -y
sudo rm -rf /var/www/*
sudo mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
cmd="
server {
        add_header X-Served-By \"$(hostname)\";
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name itszey.tech www.itszey.tech;

        error_page 404 /404.html;

        location / {
                try_files \$uri \$uri/ = 404;
        }

        location /angel {
                return 301 http://angel.itszey.tech;
        }

        location /404.html {
                internal;
                root /var/www/itszey.tech/html/;
        }

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}"

echo -e "$cmd" | sudo tee /etc/nginx/sites-enabled/default > /dev/null
sudo service nginx restart
