#!/usr/bin/env bash
# Setting up a Load balancer to connect 2 servers to a domain 
# install HAProxy 2.9
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.9 -y
sudo apt-get install haproxy=2.9.\* -y

config="\
frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    mode http
    server 132327-web-01 54.173.4.64:80 check
    server 132327-web-02 100.25.41.219:80 check
"
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null
echo -e "$config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
