#!/usr/bin/env bash
# Configure mysql backup file and compression for disk space
day=$(date '+%d')
month=$(date '+%m')
year=$(date '+%Y')
mysqldump -u root --password="$1" --all-databases > backup.sql
tar -czf "$day"-"$month"-"$year".tar.gz backup.sql
