#!/usr/bin/env bash
# Prints a string 10 times using the until loop
# Until runs the `command` UNTIL the condition is met

str="Best School"
i="0"
until [ ! $i -lt "10" ]
do
	echo "$str"
	i=$((i + 1))
done
