#!/usr/bin/env bash
# Prints a string 9 times using a while loop and a different statement in between

str="Best School"
i="0"
while [ $i -lt "10" ]
do
	echo "$str"
	if [ $i == 8 ]; then
		echo "Hi"
	fi
	i=$((i + 1))
done
