#!/usr/bin/env bash
# Checks status of a school file

if [ -e "school" ]; then 
	echo "school file exists"

	stat=$(file school | cut -d: -d' ' -f2)
	if [ "$stat" == "empty" ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [ -f "school" ]; then
		echo "school is a regular file"
	fi

else
	echo "school file does not exist"
fi
