#!/usr/bin/env bash
# Chnage the localhost a hostname to the hostfile
cp /etc/hosts ~/hosts.new
sed -i '/localhost/d' ~/hosts.new
sed -i '3a 127.0.0.2\tlocalhost' ~/hosts.new
sed -i '/facebook/d' ~/hosts.new
sed -i '4a 8.8.8.8\t\tfacebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
